// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-auWDvMBmsLEauIYQt9MJkpSfAY5Rj64',
    appId: '1:100491179298:web:156012be5ba9e15786a17b',
    messagingSenderId: '100491179298',
    projectId: 'semi-final-c2809',
    authDomain: 'semi-final-c2809.firebaseapp.com',
    storageBucket: 'semi-final-c2809.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOWiEUSUFVNeB7x78TgD-JSnWAEvHifIk',
    appId: '1:100491179298:android:2768f77e095e9f5786a17b',
    messagingSenderId: '100491179298',
    projectId: 'semi-final-c2809',
    storageBucket: 'semi-final-c2809.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZpdjWgJqJSqGwlzc8afY4Yr_gEvGhNEs',
    appId: '1:100491179298:ios:379c58a8908da1b786a17b',
    messagingSenderId: '100491179298',
    projectId: 'semi-final-c2809',
    storageBucket: 'semi-final-c2809.appspot.com',
    iosClientId: '100491179298-r9lgupglqb9odo43cho67l920me0v10s.apps.googleusercontent.com',
    iosBundleId: 'com.example.semiFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZpdjWgJqJSqGwlzc8afY4Yr_gEvGhNEs',
    appId: '1:100491179298:ios:379c58a8908da1b786a17b',
    messagingSenderId: '100491179298',
    projectId: 'semi-final-c2809',
    storageBucket: 'semi-final-c2809.appspot.com',
    iosClientId: '100491179298-r9lgupglqb9odo43cho67l920me0v10s.apps.googleusercontent.com',
    iosBundleId: 'com.example.semiFinal',
  );
}
